version: '3.8'
services:
  app:
    image: ${{ secrets.DROP_RIDE_DOCKER_USER }}/drop-app-backend:latest
    container_name: drop-app-backend
    ports:
      - "5150:5150"
    env_file:
      - .env
    restart: unless-stopped